name: Go Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CGO_ENABLED: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          args: --timeout 5m0s

      - name: Run unit tests
        run: go test -v $(go list ./... | grep -v /e2e/) -coverprofile=unit.out -covermode=atomic

      - name: Run integration tests
        run: go test -v ./e2e -coverprofile=e2e.out -covermode=atomic -coverpkg ./...

      - name: Build
        run: go build -v .

      - name: Download gocovmerge
        run: go get github.com/thedadams/gocovmerge@270276f741eede245d044932149f3ee408fffccf

      - name: Publish code climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: gocovmerge -output c.out unit.out e2e.out
          coverageLocations: ${{github.workspace}}/c.out:gocov
          prefix: github.com/thedadams/docker-machine-driver-openforked/
